name: 'GitHub CI'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    name: on ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      env:
        BROWSER: firefox-container
      run: mvn -V -ntp clean verify --file pom.xml  '-Djenkins.test.timeout=5000' '-DElasticTime.factor=2' '-Dsurefire.rerunFailingTestsCount=2'
